# Generated by Django 4.1.4 on 2023-04-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_settings_email_settings_phone_settings_slogan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='location',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
