# Generated by Django 4.1.4 on 2023-04-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_settings_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="Abrevation_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="slogan1",
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
