# Generated by Django 4.1.4 on 2023-04-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_settings_abrevation_name_settings_slogan1"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="slogan2",
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
