# Generated by Django 4.1.4 on 2023-04-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_settings_slogan2"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="descrption1",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="descrption2",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="descrption3",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
