# Generated by Django 4.1.4 on 2023-04-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_settings_descrption1_settings_descrption2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="descrption1",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="settings",
            name="descrption2",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="settings",
            name="descrption3",
            field=models.TextField(max_length=1000),
        ),
    ]
