# Generated by Django 4.1.4 on 2023-04-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_settings_background_image_settings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='background_image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
