# Generated by Django 4.1.4 on 2023-05-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_activitylog_action_activitylog_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Employee',
            field=models.BooleanField(default=False),
        ),
    ]
