# Generated by Django 4.1.4 on 2023-05-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.blocktype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Disability',
            field=models.CharField(blank=True, choices=[('Disable', 'Disable'), ('Not_Disable', 'Not_Disable')], max_length=100, null=True),
        ),
    ]
