# Generated by Django 4.1.4 on 2023-03-23 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Block_name', models.CharField(max_length=100)),
                ('Block_purpose', models.CharField(choices=[('Males Block', 'Males Block'), ('Females Block', 'Females Block')], max_length=100)),
                ('Block_Capacity', models.IntegerField()),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=150)),
                ('Block_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.blocktype')),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dorm_name', models.CharField(max_length=100)),
                ('Floor', models.CharField(choices=[('Floor-1', 'Floor-1'), ('Floor-2', 'Floor-2'), ('Floor-3', 'Floor-3'), ('Floor-4', 'Floor-4')], max_length=100)),
                ('Capacity', models.CharField(max_length=10)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=150)),
                ('Block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.block')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.block')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.dorm')),
                ('Stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
