# Generated by Django 4.1.4 on 2023-04-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDean', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='Floor',
            field=models.CharField(choices=[('Floor-1', 'Floor-1'), ('Floor-2', 'Floor-2'), ('Floor-3', 'Floor-3'), ('Floor-4', 'Floor-4'), ('Floor-5', 'Floor-5'), ('Floor-6', 'Floor-6'), ('Floor-7', 'Floor-7')], max_length=100),
        ),
    ]
