# Generated by Django 4.1.4 on 2023-05-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDean', '0002_alter_dorm_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, null=True)),
                ('Content', models.TextField(max_length=3000, null=True)),
                ('Image', models.FileField(null=True, upload_to='files/')),
                ('Active_Date', models.DateTimeField()),
                ('End_Date', models.DateTimeField()),
            ],
        ),
    ]
