# Generated by Django 4.1.4 on 2023-05-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StudentDean", "0003_announcement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="Image",
        ),
        migrations.AddField(
            model_name="announcement",
            name="File",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="Content",
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
