# Generated by Django 4.1.4 on 2023-05-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDean', '0004_remove_announcement_image_announcement_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Active_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='End_Date',
            field=models.DateField(),
        ),
    ]
