# Generated by Django 4.1.4 on 2023-03-23 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StudentDean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_id', models.CharField(max_length=100, unique=True)),
                ('Propery_name', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.block')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.dorm')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bed', to='Proctor.properties')),
                ('Chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chair', to='Proctor.properties')),
                ('Desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Desk', to='Proctor.properties')),
                ('Locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Locker', to='Proctor.properties')),
                ('Mattress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mattress', to='Proctor.properties')),
                ('Pillow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pillow', to='Proctor.properties')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key', to='Proctor.properties')),
                ('proctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bed1', to='Proctor.properties')),
                ('Chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chair1', to='Proctor.properties')),
                ('Desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Desk1', to='Proctor.properties')),
                ('Locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Locker1', to='Proctor.properties')),
                ('Mattress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mattress1', to='Proctor.properties')),
                ('Pillow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pillow1', to='Proctor.properties')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key1', to='Proctor.properties')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
