# Generated by Django 4.1.4 on 2023-03-23 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow_request',
            name='Bed',
        ),
        migrations.RemoveField(
            model_name='borrow_request',
            name='Chair',
        ),
        migrations.RemoveField(
            model_name='borrow_request',
            name='Desk',
        ),
        migrations.RemoveField(
            model_name='borrow_request',
            name='Locker',
        ),
        migrations.RemoveField(
            model_name='borrow_request',
            name='Mattress',
        ),
        migrations.RemoveField(
            model_name='borrow_request',
            name='Pillow',
        ),
        migrations.RemoveField(
            model_name='borrow_request',
            name='key',
        ),
        migrations.RemoveField(
            model_name='material',
            name='Bed',
        ),
        migrations.RemoveField(
            model_name='material',
            name='Chair',
        ),
        migrations.RemoveField(
            model_name='material',
            name='Desk',
        ),
        migrations.RemoveField(
            model_name='material',
            name='Locker',
        ),
        migrations.RemoveField(
            model_name='material',
            name='Mattress',
        ),
        migrations.RemoveField(
            model_name='material',
            name='Pillow',
        ),
        migrations.RemoveField(
            model_name='material',
            name='key',
        ),
        migrations.AddField(
            model_name='borrow_request',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property1', to='Proctor.properties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='Proctor.properties'),
            preserve_default=False,
        ),
    ]
