# Generated by Django 4.1.4 on 2023-03-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proctor', '0002_remove_borrow_request_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_category',
            field=models.CharField(choices=[('Key', 'Key'), ('Locker', 'Locker'), ('Desk', 'Desk'), ('Chair', 'Chair'), ('Bed', 'Bed'), ('Mattress', 'Mattress'), ('Pillow', 'Pillow')], default=1, max_length=150),
            preserve_default=False,
        ),
    ]
