# Generated by Django 4.1.4 on 2023-03-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proctor', '0004_exit_permission_requst_exit_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit_permission_requst',
            name='date',
            field=models.DateField(),
        ),
    ]
