# Generated by Django 4.1.4 on 2023-05-31 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proctor', '0005_alter_exit_permission_requst_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit_permission',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='ReportProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_solve', models.CharField(default='Un-Approved', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
