# Generated by Django 4.1.4 on 2023-04-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorschedule',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Nigth', 'Nigth')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
