# Generated by Django 4.1.4 on 2023-04-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0002_proctorschedule_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorschedule',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
