# Generated by Django 4.1.4 on 2023-04-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0003_proctorschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctorschedule',
            name='date',
            field=models.DateField(),
        ),
    ]
