# Generated by Django 4.1.4 on 2023-04-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0005_alter_proctorschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctorschedule',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Nigth', 'Nigth')], max_length=10, null=True),
        ),
    ]
