# Generated by Django 4.1.4 on 2023-05-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0007_proctorassignment_schedule_delete_proctorschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='num_shift_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shift',
            field=models.CharField(max_length=10),
        ),
    ]
